// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBlamP32PyQDEH-aKKBMllRAamizk-ViY',
    appId: '1:37956014100:web:1f881020624b9643245701',
    messagingSenderId: '37956014100',
    projectId: 'smart-route-planner-78cd3',
    authDomain: 'smart-route-planner-78cd3.firebaseapp.com',
    storageBucket: 'smart-route-planner-78cd3.firebasestorage.app',
    measurementId: 'G-BMKMF0ZGJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtDQmY1mKYt2WKXF2LsXwW3IdzK7kKST8',
    appId: '1:37956014100:android:1bfef12ea736124c245701',
    messagingSenderId: '37956014100',
    projectId: 'smart-route-planner-78cd3',
    storageBucket: 'smart-route-planner-78cd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwmb4tF0oMa_XK63aBk1iDdB3fL-Wrj1s',
    appId: '1:37956014100:ios:13f596ea139b29fe245701',
    messagingSenderId: '37956014100',
    projectId: 'smart-route-planner-78cd3',
    storageBucket: 'smart-route-planner-78cd3.firebasestorage.app',
    androidClientId: '37956014100-2dp0kgs2ubr06ssjum5gh31pq03a89aa.apps.googleusercontent.com',
    iosClientId: '37956014100-96c1rppfk0n61u221lmh8u0pav9e309j.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartRoutePlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwmb4tF0oMa_XK63aBk1iDdB3fL-Wrj1s',
    appId: '1:37956014100:ios:13f596ea139b29fe245701',
    messagingSenderId: '37956014100',
    projectId: 'smart-route-planner-78cd3',
    storageBucket: 'smart-route-planner-78cd3.firebasestorage.app',
    androidClientId: '37956014100-2dp0kgs2ubr06ssjum5gh31pq03a89aa.apps.googleusercontent.com',
    iosClientId: '37956014100-96c1rppfk0n61u221lmh8u0pav9e309j.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartRoutePlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBlamP32PyQDEH-aKKBMllRAamizk-ViY',
    appId: '1:37956014100:web:479bfa90cb52b485245701',
    messagingSenderId: '37956014100',
    projectId: 'smart-route-planner-78cd3',
    authDomain: 'smart-route-planner-78cd3.firebaseapp.com',
    storageBucket: 'smart-route-planner-78cd3.firebasestorage.app',
    measurementId: 'G-2MPZQR01WB',
  );
}
