// lib/main.dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'dart:async';
import 'package:permission_handler/permission_handler.dart';
import 'package:flutter_polyline_points/flutter_polyline_points.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart'; // Import Firebase Core
import 'auth_gate.dart'; // Import the AuthGate
import 'auth_service.dart'; // Import for sign out
import 'firebase_options.dart'; // Generated by the FlutterFire CLI

// Backend URL for your deployed service
const String backendUrl =
    'https://smart-route-planner-888766503240.asia-south1.run.app';
// API Key loaded from the .env file
final String googleApiKey =
    dotenv.env['GOOGLE_MAPS_API_KEY'] ?? 'YOUR_DEFAULT_API_KEY';

Future<void> main() async {
  // Ensure that widgets are initialized before running the app
  WidgetsFlutterBinding.ensureInitialized();
  // Load environment variables from the .env file
  await dotenv.load(fileName: ".env");
  // --- NEW: Initialize Firebase for authentication ---
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Smart Route Planner',
      theme: ThemeData(primarySwatch: Colors.deepOrange, useMaterial3: true),
      debugShowCheckedModeBanner: false,
      // --- MODIFIED: Use AuthGate as the home to handle login state ---
      home: const AuthGate(),
    );
  }
}

// The main map screen of the application
class MapScreen extends StatefulWidget {
  const MapScreen({super.key});

  @override
  State<MapScreen> createState() => _MapScreenState();
}

class _MapScreenState extends State<MapScreen> {
  final Completer<GoogleMapController> _controller = Completer();

  static const CameraPosition _initialPosition = CameraPosition(
    target: LatLng(19.0760, 72.8777), // Centered on Mumbai
    zoom: 12,
  );

  final Set<Marker> _markers = {};
  final Set<Polyline> _polylines = {};
  LatLng? _origin;
  LatLng? _destination;
  bool _isLoading = false;
  bool _isLocationPermissionGranted = false;
  final PolylinePoints _polylinePoints = PolylinePoints();

  TravelMode _travelMode = TravelMode.driving;

  @override
  void initState() {
    super.initState();
    _requestLocationPermission();
  }

  Future<void> _requestLocationPermission() async {
    final status = await Permission.location.request();
    if (status.isGranted) {
      setState(() {
        _isLocationPermissionGranted = true;
      });
    } else if (status.isPermanentlyDenied) {
      openAppSettings();
    }
  }

  void _onMapTapped(LatLng location) {
    setState(() {
      _polylines.clear();
      if (_origin == null || (_origin != null && _destination != null)) {
        _origin = location;
        _destination = null;
        _markers.clear();
        _markers.add(
          Marker(
            markerId: const MarkerId('origin'),
            position: _origin!,
            icon: BitmapDescriptor.defaultMarkerWithHue(
              BitmapDescriptor.hueGreen,
            ),
            infoWindow: const InfoWindow(title: 'Origin'),
          ),
        );
      } else {
        _destination = location;
        _markers.add(
          Marker(
            markerId: const MarkerId('destination'),
            position: _destination!,
            icon: BitmapDescriptor.defaultMarkerWithHue(
              BitmapDescriptor.hueRed,
            ),
            infoWindow: const InfoWindow(title: 'Destination'),
          ),
        );
        _getRoute();
      }
    });
  }

  Future<void> _getRoute() async {
    if (_origin == null || _destination == null) return;

    setState(() {
      _isLoading = true;
    });

    try {
      final response = await http.post(
        Uri.parse('$backendUrl/route'),
        headers: {'Content-Type': 'application/json'},
        body: json.encode({
          'origin': {'lat': _origin!.latitude, 'lng': _origin!.longitude},
          'destination': {
            'lat': _destination!.latitude,
            'lng': _destination!.longitude,
          },
        }),
      );

      if (response.statusCode == 200) {
        final dynamic decodedBody = json.decode(response.body);
        if (decodedBody is List && decodedBody.length >= 2) {
          List<LatLng> waypoints = decodedBody
              .map((p) => LatLng(p['lat'], p['lng']))
              .toList();

          const int maxWaypoints = 23;
          if (waypoints.length > maxWaypoints) {
            final List<LatLng> simplifiedWaypoints = [waypoints.first];
            final int step = (waypoints.length - 2) ~/ (maxWaypoints - 2);
            for (int i = 1; i < waypoints.length - 1; i += step) {
              if (simplifiedWaypoints.length < maxWaypoints - 1) {
                simplifiedWaypoints.add(waypoints[i]);
              }
            }
            simplifiedWaypoints.add(waypoints.last);
            waypoints = simplifiedWaypoints;
          }

          final PolylineResult result = await _polylinePoints
              .getRouteBetweenCoordinates(
                request: PolylineRequest(
                  origin: PointLatLng(
                    waypoints.first.latitude,
                    waypoints.first.longitude,
                  ),
                  destination: PointLatLng(
                    waypoints.last.latitude,
                    waypoints.last.longitude,
                  ),
                  mode: _travelMode,
                  wayPoints: waypoints
                      .sublist(1, waypoints.length - 1)
                      .map(
                        (latlng) => PolylineWayPoint(
                          location: "${latlng.latitude},${latlng.longitude}",
                        ),
                      )
                      .toList(),
                ),
                googleApiKey: googleApiKey,
              );

          if (result.points.isNotEmpty) {
            final List<LatLng> polylineCoordinates = result.points
                .map((point) => LatLng(point.latitude, point.longitude))
                .toList();
            setState(() {
              _polylines.add(
                Polyline(
                  polylineId: const PolylineId('route'),
                  points: polylineCoordinates,
                  color: Colors.deepOrange,
                  width: 6,
                ),
              );
            });

            final GoogleMapController controller = await _controller.future;
            controller.animateCamera(
              CameraUpdate.newLatLngBounds(
                _createLatLngBounds(polylineCoordinates),
                100.0,
              ),
            );
          } else {
            throw Exception('Could not get route: ${result.errorMessage}');
          }
        } else {
          throw Exception('Invalid waypoint data from server.');
        }
      } else {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Error from backend: ${response.body}')),
          );
        }
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('An error occurred: $e')));
      }
    } finally {
      setState(() {
        _isLoading = false;
      });
    }
  }

  LatLngBounds _createLatLngBounds(List<LatLng> positions) {
    final southwest = positions.reduce(
      (value, element) => LatLng(
        value.latitude < element.latitude ? value.latitude : element.latitude,
        value.longitude < element.longitude
            ? value.longitude
            : element.longitude,
      ),
    );
    final northeast = positions.reduce(
      (value, element) => LatLng(
        value.latitude > element.latitude ? value.latitude : element.latitude,
        value.longitude > element.longitude
            ? value.longitude
            : element.longitude,
      ),
    );
    return LatLngBounds(southwest: southwest, northeast: northeast);
  }

  void _resetMap() {
    setState(() {
      _markers.clear();
      _polylines.clear();
      _origin = null;
      _destination = null;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Smart Route Planner'),
        actions: [
          if (_isLoading)
            const Padding(
              padding: EdgeInsets.only(right: 20.0),
              child: Center(
                child: CircularProgressIndicator(color: Colors.white),
              ),
            ),
          // --- NEW: Sign Out Button ---
          IconButton(
            icon: const Icon(Icons.logout),
            tooltip: 'Sign Out',
            onPressed: () => AuthService().signOut(),
          ),
        ],
      ),
      body: Stack(
        children: [
          GoogleMap(
            initialCameraPosition: _initialPosition,
            onMapCreated: (GoogleMapController controller) {
              _controller.complete(controller);
            },
            onTap: _onMapTapped,
            markers: _markers,
            polylines: _polylines,
            myLocationEnabled: _isLocationPermissionGranted,
            myLocationButtonEnabled: _isLocationPermissionGranted,
            zoomControlsEnabled: false,
          ),
          Positioned(
            top: 10,
            left: 0,
            right: 0,
            child: Center(
              child: Wrap(
                spacing: 8.0,
                children: [
                  ChoiceChip(
                    label: const Text('Driving'),
                    selected: _travelMode == TravelMode.driving,
                    onSelected: (selected) {
                      setState(() => _travelMode = TravelMode.driving);
                      if (_origin != null && _destination != null) _getRoute();
                    },
                    avatar: const Icon(Icons.directions_car),
                  ),
                  ChoiceChip(
                    label: const Text('Walking'),
                    selected: _travelMode == TravelMode.walking,
                    onSelected: (selected) {
                      setState(() => _travelMode = TravelMode.walking);
                      if (_origin != null && _destination != null) _getRoute();
                    },
                    avatar: const Icon(Icons.directions_walk),
                  ),
                  ChoiceChip(
                    label: const Text('Biking'),
                    selected: _travelMode == TravelMode.bicycling,
                    onSelected: (selected) {
                      setState(() => _travelMode = TravelMode.bicycling);
                      if (_origin != null && _destination != null) _getRoute();
                    },
                    avatar: const Icon(Icons.directions_bike),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _resetMap,
        tooltip: 'Clear',
        child: const Icon(Icons.clear),
      ),
    );
  }
}
