name: smart_route_planner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0' # It's good practice to use a range

dependencies:
  flutter:
    sdk: flutter

  # Core Functionality
  google_maps_flutter: ^2.5.0
  http: ^1.2.1
  permission_handler: ^11.3.1 # Updated to a more recent version
  flutter_polyline_points: ^2.0.0

  # Firebase Authentication
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1

  # API Key Management
  flutter_dotenv: ^5.1.0
  
  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Updated to a more recent version

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/

